version: "2"
networks: 
    app_bridge:
        driver: bridge
services: 
    nginx:
        image: nginx
        container_name: sharetheshop_nginx_container
        restart: always
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - api
        networks:
            - app_bridge

    api:
        image: siouija/sharetheshop
        container_name: sharetheshop_api_container
        restart: always
        networks: 
            - app_bridge